name: Run tests suite

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: windows-2019
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Perform Pester tests
        shell: pwsh
        run: |
          Invoke-Pester Tests\* -Passthru
